DOMAIN = "vodafone_router_device_polling"

DEFAULT_SCAN_INTERVAL = 30

ENTRY_DATA_HOST = "host"
OPTION_USERNAME = "username"
OPTION_PASSWORD = "password"
OPTION_SCAN_INTERVAL = "scan_interval"

ROUTER_PROPERTY_LAN_DEVICES = "lanDevices"
ROUTER_PROPERTY_WLAN_DEVICES = "wlanDevices"

DEVICE_PROPERTY_MAC_ADDRESS = "MAC"
DEVICE_PROPERTY_HOSTNAME = "HostName"
DEVICE_PROPERTY_IP_ADDRESS = "IP"
DEVICE_PROPERTY_NAME = "name"